### ISSUE TITLE
Open editor on windows environment

### ISSUE THREAD

**Issue by dragoblaztr** [hagronnestad/nextion-font-editor#1]
First of all congratulations and thanks for developing this project, I'm digging at web looking for a bes tool for create and edit nextion's fonts, however I would to know ho to execute it?

Thanks in advance

**Comment by hagronnestad** [comment]
I only started working on this tool a few days. I've already come a long way, but you won't be able to use the application as is yet. I'm working a lot on this project at the moment though, so stay tuned.
