### ISSUE TITLE
Font size flexibility

### ISSUE THREAD

**Issue by tvkit** [hagronnestad/nextion-font-editor#6]
Perhaps I'm overlooking something, but it seems the target font size is locked to multiples of 8. If so, is that an implementation limitation or a Nextion limitation?

BTW, thank you for publishing your findings. The anti-aliasing referenced in the new spec looks promising.

**Comment by hagronnestad** [comment]
Yes, the fint sizes are all multiples of 8. I think I just used the same values as the original font generator to be honest, but as long as the font size is a multiple of 2 it should work I guess. For version 3, the width is always half the height, so the height has to be divisible by 2. The new version, version 5, has both variable width fonts and anti aliasing.

I just changed the font sizes to be multiples of 2 in this commit: d7c28a00d68527c46e96553ccd4f9a9c144301a6

Could you give it a try @tvkit?

(Also, @fvanroie did a lot of the research on the new font format so far, so thank him too 😄)

**Comment by hagronnestad** [comment]
Binaries from the latest build can be found here: https://ci.appveyor.com/project/hagronnestad/nextion-font-editor/build/artifacts

**Comment by tvkit** [comment]
Thank you, @hagronnestad !

Using the latest from the master branch with the **All Max Size** option selected, here's what I'm seeing in the Nextion Editor:  (btw, I modified the Font args to include **FontStyle.Bold** which was used for both font generations)

![image](https://user-images.githubusercontent.com/28468364/53656360-0d863f80-3c21-11e9-9fae-9f27142ea9e4.png)

**Comment by tvkit** [comment]
@hagronnestad  after digging deeper into this issue, it seems the ZI height must be mod 8.  So consider backing out the changes that allow for non-mod-8 Nextion Font Sizes.

**Comment by hagronnestad** [comment]
🤦‍♂️ of course, I remember now. The pixel data has to be byte aligned... I will revert the commit.

**Comment by hagronnestad** [comment]
I reverted the changes in this commit: 3420ecc7984207a8409e5b8c75d912464bcde5a3
